name: 🚀

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '16'
      - name: Build
        run: yarn && yarn build
        env:
          NODE_AUTH_TOKEN: ${{secrets.PAT}}
      - name: Release
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          yarn ci:release
        env:
          GH_TOKEN: ${{ secrets.CI_PAT }}
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
